global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'kafka'
#    static_configs:
#      - targets: ['kafka-exporter:5556']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']

  - job_name: 'bidding-service'
    static_configs:
      - targets: ['app:9100']