{
 "title": "SAMBERNGALOW SOLAR",
 "description": "Our solar monitor!",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Charging State",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solarshed_controller_charging_state"
    }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "expr": "solarshed_solar_volts" }
   ]
  },
  {
   "title": "Solar Amps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    { "expr": "solarshed_solar_amperes" }
   ]
  },
  {
   "title": "Solar Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    { "expr": "solarshed_solar_watts" }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "solarshed_battery_percentage" }
   ]
  },
  {
   "title": "Charging State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "state" }
   ],
   "targets": [
    {
     "expr": "solarshed_controller_charging_state"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "solarshed_battery_volts" }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "solarshed_solar_volts" }
   ]
  },
  {
   "title": "Load Amps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "solarshed_load_amperes" }
   ]
  },
  {
   "title": "Solar Amps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "solarshed_solar_amperes" }
   ]
  },
  {
   "title": "Load Watts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "solarshed_load_power_watts" }
   ]
  },
  {
   "title": "Solar Watts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "solarshed_solar_watts" }
   ]
  },
  {
   "title": "Battery Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "solarshed_battery_temperature_celsius * 1.8 + 32"
    }
   ]
  },
  {
   "title": "Controller Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "solarshed_controller_temperature_celsius * 1.8 + 32"
    }
   ]
  },
  {
   "title": "Battery Temperature (C)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "solarshed_battery_temperature_celsius"
    }
   ]
  },
  {
   "title": "Controller Temperature (C)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "solarshed_controller_temperature_celsius"
    }
   ]
  }
 ]
}